auteur = "Andréanne Grenier"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/couverture.png"
description = "Voici des poèmes que j'ai réalisés dans le cadre de deux cours de mon Baccalauréat en littérature de langue française et des photos que j'ai prises durant la dernière année."
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Sous-titre"
titre = "Poèmes à moi"
